Solution
Strandol/javascript-task-1 pull request #1
Opened 2017-01-09 18:38 UTC by Strandol

2017-01-09 19:56 UTC, DudaGod commented on roman-time.js
> +    var hours = time.slice(0, 2);
а если я одну цифру укажу? Правильнее будет вырезать до двоеточия

2017-01-09 19:58 UTC, DudaGod commented on roman-time.js
> +    var minutes = time.slice(3, 5);
а если у меня три цифры в конце будет?

2017-01-09 20:21 UTC, DudaGod commented on roman-time.js
> +        return convertNumber(str, isHours);
как думаешь это норм, что у тебя функцию называется - `checkNumber`, а на самом деле внутри себя запускает конвертацию в число?

2017-01-09 20:31 UTC, DudaGod requested changes

2017-01-09 20:31 UTC, DudaGod commented on roman-time.js
> +function checkNumber(str, isHours) {
давай вместо этой напишем функцию - `isTimeValid` в которую ты будешь передавать сразу и часы и минуты. Она будет проверять не только на `NaN`, но и на пределы. Минут же не может быть больше чем 59? И возвращать `true` если все норм и `false` если все плохо.

2017-01-09 20:31 UTC, DudaGod commented on roman-time.js
> +    if (!isNaN(parseInt(str))) {
условие без инверсии читает легче в данном случае

2017-01-09 20:31 UTC, DudaGod commented on roman-time.js
> +    if (num === '00') {
а если я просто ноль указал, вместо двух нулей?

2017-01-09 20:31 UTC, DudaGod commented on roman-time.js
> +        throwError();
у тебя же для этого есть специальная функция в которой ты все это должен проверить. Зачем ты это тут проверяешь?

2017-01-09 20:31 UTC, DudaGod commented on roman-time.js
> +    num = '';
зачем ты тут присваиваешь пустую строку и передаешь ее в обе функции? Можно же намного красивее тут сделать

2017-01-09 20:31 UTC, DudaGod commented on roman-time.js
> +    return num;
ты не замечаешь что у тебя условия в этих двух функциях - `convertDecade` и `convertOne` очень похожи?
Давай их попробуем одной функцией написать. И это вполне реально.

2017-01-09 20:31 UTC, DudaGod commented on roman-time.js
> +    return num;
И названия у этих функций так себе на самом деле.

2017-01-12 22:50 UTC, Strandol commented on roman-time.js
> +    var hours = time.slice(0, 2);
@DudaGod Одну нельзя, но я подумаю

2017-01-18 18:34 UTC, DudaGod commented on roman-time.js
> +function throwError() {
зачем тебе эта функция?
Она же используется только в одном месте. Лучше вставь ее внутренний код на то место где ты ее вызываешь, будет намного понятнее

2017-01-18 18:35 UTC, DudaGod commented on roman-time.js
> +        throwError();
эта функция не должна бросать ошибку. Ее область ответственности - это определить валидное время переданно или нет. То есть вернуть `true` или `false`

2017-01-18 18:36 UTC, DudaGod commented on roman-time.js
> +    }
вот тут условие инвертируй.
Если условие не верно брось ошибку. А ниже сразу же можешь без `else` - меньше вложенность будет -> легче читать.

2017-01-18 18:38 UTC, DudaGod commented on roman-time.js
> +        return time;
зачем тебе тут возвращать время? Ты же его просто отрисуешь в консоль и все.

2017-01-18 18:39 UTC, DudaGod commented on roman-time.js
> +        drawRomanTime(time);
а если тебе не нужно время возвращать, то ты можешь сразу сделать код проще. Не переопределять аргумент `time`:
```js
drawRomanTime(convertNumber(hours) + ':' + convertNumber(minutes));
```

2017-01-18 18:49 UTC, DudaGod commented on roman-time.js
> +function convertNumber(num) {
давай назовем `parseToRomanNum`

2017-01-18 18:50 UTC, DudaGod commented on roman-time.js
> +    if (Number(hours) > 23 || Number(minutes) > 59 || Number(hours) < 0 || Number(minutes) < 0) {
зачем ты это здесь проверяешь?
У тебя же уже есть функция для проверки валидное время было передано или нет

2017-01-18 18:54 UTC, Strandol commented on roman-time.js
> +    if (Number(hours) > 23 || Number(minutes) > 59 || Number(hours) < 0 || Number(minutes) < 0) {
@DudaGod Это в границы, а то валидное или нет

2017-01-18 18:58 UTC, Strandol commented on roman-time.js
> +        return time;
@DudaGod В задании сказано возвращать время

2017-01-18 18:58 UTC, Strandol commented on roman-time.js
> +        return time;
@DudaGod По нем видимо тесты проходят

2017-01-18 19:07 UTC, DudaGod commented on roman-time.js
> +    return false;
тут можно драматически улучшить эту функцию:
```js
function isNotNan(val) {
  return !isNaN(parseInt(val));
}

function isTimeBetween(val, min, max) {
  return val > min && val <= max;
}

function isTImeValid(hours, minutes) {
  return isNotNan(hours) && isTimeBetween(hours, 0, 24) && isNotNan(minutes) && isTimeBetween(minutes, 0, 59);
}
```

2017-01-19 21:31 UTC, DudaGod commented on roman-time.js
> +        return time;
ок

2017-01-19 21:33 UTC, DudaGod commented on roman-time.js
> +    return num;
зачем тебе тут локальная переменная? Сразу возвращай зачение

2017-01-19 22:10 UTC, DudaGod commented on roman-time.js
> +}
не очень красивая функция получилась. Все это делается намного легче.

2017-01-23 15:32 UTC, Strandol commented on roman-time.js
> +    return false;
@DudaGod Строка по правилам слишком длинная, так что мой вариант норм)

2017-01-23 18:42 UTC, DudaGod commented on roman-time.js
> +};
чего ты не хочешь здесь правильный порядок сделать? По нормальному же 1 идет раньше 50 ти.

2017-01-23 18:44 UTC, DudaGod commented on roman-time.js
> +};
пока не понял зачем тебе этот объект... Кажется, что можно без него написать.

2017-01-23 18:53 UTC, DudaGod commented on roman-time.js
> +    var timeInStr = time.match(/(\d){1,2}:(\d){1,2}/);
не правильно скобки тут поставил

2017-01-23 18:55 UTC, DudaGod commented on roman-time.js
> +    var minutes = timeInStr[0].split(':')[1];
Давай может так:
```js
var hours = time.match(/(\d{1,2}):/)[1];
var minutes = time.match(/:(\d{1,2})/)[1];
```

2017-01-23 18:55 UTC, DudaGod commented on roman-time.js
> +    result = [];
у тебя эти две переменные и выше есть на строках 62-63

2017-01-23 18:57 UTC, DudaGod commented on roman-time.js
> +}
Илья мы же с тобой говорили про эту функцию. Она не должна бросать ошибку. Она должна вернуть только `true` или `false`. Так как она может быть где то еще использована. А ты прям в нее зашил, что она должна ошибки кидать еще с определенным текстом

2017-01-23 18:58 UTC, DudaGod commented on roman-time.js
> +    }
зачем такая вложенность?
Инверсируй условие:
```js
if (!isTimeValid(hours, minutes)) {
  throw error;
}

// дальше твой код
```

2017-01-23 18:59 UTC, DudaGod commented on roman-time.js
> +        parseToRomanNum(hours);
описание этой функции должно быть раньше чем -`showRomanTime`

2017-01-23 19:00 UTC, DudaGod commented on roman-time.js
> +    result = [];
и кажется можно вообще без них сделать

2017-01-23 19:02 UTC, DudaGod commented on roman-time.js
> +    if (Number(hours) > 23 || Number(minutes) > 59 || Number(hours) < 0 || Number(minutes) < 0) {
не чувствуешь дублирования? Нафига тебе каждый раз оборачивать твои строки `hours` и `minutes` в `Number`? Вызови `parseInt` при получении часов и минут

2017-01-23 19:05 UTC, DudaGod commented on roman-time.js
> +    var minutes = timeInStr[0].split(':')[1];
чтобы получить числа можешь сразу же так сделать и не парится внизу с обертками `Number`:
```js
var hours = parseInt(time.match(/(\d{1,2}):/)[1]);
var minutes = parseInt(time.match(/:(\d{1,2})/)[1]);
```

2017-01-23 19:08 UTC, DudaGod commented on roman-time.js
> +    return true;
и зачем тебе тут хардкодить `true` и `false`? Можно же сразу вернуть твое условие:
```js
return Number(hours) > 23 || Number(minutes) > 59 || Number(hours) < 0 || Number(minutes) < 0
```
Только его нужно изменить чуть-чуть, чтобы оно возвращало `true` если валидно и `false` если нет

2017-01-23 19:08 UTC, DudaGod commented on roman-time.js
> +
нафига этот отступ?

2017-01-23 19:08 UTC, DudaGod commented on roman-time.js
> +    for (var j = 0; j < AsciiTime[1].length; j++) {
обычно начинают обход с i

2017-01-23 19:11 UTC, DudaGod commented on roman-time.js
> +        return;
это плохо когда у тебя функция ничего не возвращает.
Зачем так делать? Не нужен тебе тут глобальный `result` - сделай без него

2017-01-23 19:12 UTC, DudaGod commented on roman-time.js
> +    ':': [
чтобы понятнее было назови это `colon`, а не просто две точки какие то

2017-01-23 19:14 UTC, DudaGod commented on roman-time.js
> +        showRomanTime();
```js
var result = parseToRomanNum(hours).concat('colon', parseToRomanNum(minutes));
```

Т.е. в `result` давай хранить именно ключи которые тебе нужны будут, чтобы нарисовать ascii графику

2017-01-23 19:16 UTC, DudaGod commented on roman-time.js
> +        showRomanTime();
а лучше ее назвать `romanTime` какой нибудь

2017-01-23 19:16 UTC, DudaGod commented on roman-time.js
> +        return resultStr;
а здесь ты должен не строку вернуть, которая хрен поймешь где определилась - читая код сверху вниз. А вызвать функцию:
```js
renderToAscii(romanTime)
```

2017-01-23 19:17 UTC, DudaGod commented on roman-time.js
> +        return resultStr;
и тут же ниже если тебе нужно по заданию вернуть получившееся число
Хотя мне кажется его можно нарушить, так как ты в консоль выводишь, это круче.

2017-01-23 19:18 UTC, DudaGod commented on roman-time.js
> +    console.log(lineForShow);
давай юзнем все таки `process.stdout.write`. Тогда можно вообще без этой переменной обойтись

2017-01-23 19:19 UTC, DudaGod commented on roman-time.js
> +    if (num === '00' || num === '0') {
если распарсишь выше как я тебе предлагал, тут сильно упростится проверка

2017-01-23 19:20 UTC, DudaGod commented on roman-time.js
> +function parseToRomanNum(num) {
а тут ты должен создавать какой то массив который будешь заполнять и потом вернешь его

2017-01-23 19:21 UTC, DudaGod commented on roman-time.js
> +    return num;
и ты хочешь сказать, что эта твоя функция легче? ) Она намного запутанее и строк в 3 раза больше.

2017-01-23 19:21 UTC, DudaGod commented on roman-time.js
> +function pushAndReturnNewArabicNumber(num, i) {
и что это за название такое лютое? )

2017-01-23 19:22 UTC, DudaGod commented on roman-time.js
> +            resultStr += RomanNumbers[[arabicNumbers[i + 1]]];
ты тут строку не должен заполнять, за это должна отвечать другая функция.

2017-01-23 19:22 UTC, DudaGod commented on roman-time.js
> +    return num;
если про строку все убрать будет полегче

2017-01-24 20:26 UTC, Strandol commented on roman-time.js
> +};
@DudaGod  Без него не смогу нормально закидать в строку нужные буквы

2017-01-24 20:34 UTC, Strandol commented on roman-time.js
> +function parseToRomanNum(num) {
@DudaGod это мне надо будет создать массив в RomanTime функции?

2017-01-24 20:39 UTC, DudaGod commented on roman-time.js
> +function parseToRomanNum(num) {
да

2017-01-30 17:33 UTC, DudaGod commented on package.json
> +    "process": "0.11.9"
удали эту зависимость, договорились не юзать ее

2017-01-30 17:33 UTC, DudaGod commented on roman-time.js
> +};
в этом объекте порядок не поменял, а в `asciiTime` изменил, давай тут тоже изменим

2017-01-30 17:33 UTC, DudaGod commented on roman-time.js
>  function romanTime(time) {
имя функции должно начинаться с глагола, например - `parseToRoman`

2017-01-30 17:33 UTC, DudaGod commented on roman-time.js
> +    romTime = parseToRomanNum(hours).concat(parseToRomanNum(':'), parseToRomanNum(minutes));
Илья зачем ты переменную `romTime` вверху определил? Объявляй ее прям тут, она же до этого не юзается и назови ее `romanTime` - так понятнее будет

2017-01-30 17:33 UTC, DudaGod commented on roman-time.js
> +        throw new TypeError('Введите корректное значение времени!');
текст ошибки должен быть на English

2017-01-30 17:33 UTC, DudaGod commented on roman-time.js
> +    showRomanTime(romTime);
давай ее назовем `renderToAscii`

2017-01-30 17:33 UTC, DudaGod commented on roman-time.js
> +    return getStrRepOfRomanNum(hours) + ':' + getStrRepOfRomanNum(minutes);
```js
return toRomanString(hours, minutes);
```

Так же понятнее, чем `getStrRepOfRomanNum` по названию я вообще не пойму что эта функция делает

2017-01-30 17:33 UTC, DudaGod commented on roman-time.js
> +        resultArr.push(numArr[arabicNumbers[i]]);
вот так очень плохо делать. Ты модифицируешь параметр который дальше юзаешь в методе - `getStrRepOfRomanNum`. Так делать нельзя.

2017-01-30 17:33 UTC, DudaGod commented on roman-time.js
> +        num = pushNewArabicNumber(arrayOfNum, AsciiTime, Number(num), i);
вернул значение в `num` и дальше с ним нефига вообще не делаешь... Так тоже не правильно делать.

2017-01-30 17:33 UTC, DudaGod commented on roman-time.js
> +        num = pushNewArabicNumber(resultArr, RomanNumbers, num, i);
запомни функция не должна принимать столько много параметров, это совсем нечистый код =)
Максимум 2 параметра, в самых редких случаях - 3, но не четыре!
Если нужны прям все опции обычно фигачат объект в который добвляют нужные опции.

В итоге результат вызова записываешь в `num` который дальше в этой фукнции не юзается.

2017-01-30 17:40 UTC, Strandol commented on roman-time.js
> +    romTime = parseToRomanNum(hours).concat(parseToRomanNum(':'), parseToRomanNum(minutes));
@DudaGod Имя функции такое же

2017-01-30 17:41 UTC, Strandol commented on roman-time.js
> +    return getStrRepOfRomanNum(hours) + ':' + getStrRepOfRomanNum(minutes);
@DudaGod в смысле, получить строковое представление числа

2017-01-30 17:41 UTC, Strandol commented on roman-time.js
> +    return getStrRepOfRomanNum(hours) + ':' + getStrRepOfRomanNum(minutes);
@DudaGod String Representation

2017-01-30 17:44 UTC, Strandol commented on roman-time.js
> +        num = pushNewArabicNumber(resultArr, RomanNumbers, num, i);
@DudaGod я получил результат, и заново юзаю pushNewArabicNumber - и там снова num попадает, куда же еще записать num

2017-01-30 17:45 UTC, Strandol commented on roman-time.js
> +        resultArr.push(numArr[arabicNumbers[i]]);
@DudaGod В смысле? что тут не так? не пойму

2017-01-30 18:14 UTC, merged